import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { ExpenseCategory, ExpenseItem } from '../../types';
import { 
  BarChart3, 
  Download, 
  Printer, 
  Calendar, 
  Filter, 
  PieChart, 
  TrendingUp, 
  CheckCircle, 
  Building, 
  DollarSign, 
  FileSpreadsheet,
  Layers,
  ArrowUpRight,
  ShieldAlert
} from 'lucide-react';
import { downloadCSV, exportExpensesToCSV } from '../../utils/exportUtils';

export const FinancialDashboard: React.FC = () => {
  const { expenses, currentUser, hpcRows, reconciliation } = useApp();

  const [selectedMonth, setSelectedMonth] = useState('2026-10');
  const [selectedDept, setSelectedDept] = useState('All');
  const [isReportModalOpen, setIsReportModalOpen] = useState(false);

  // Filter expenses by selected period & department
  const periodExpenses = expenses.filter(exp => {
    const matchesMonth = selectedMonth === 'ALL' || exp.date.startsWith(selectedMonth);
    const matchesDept = selectedDept === 'All' || exp.department === selectedDept;
    return matchesMonth && matchesDept;
  });

  const totalExpenseAmount = periodExpenses.reduce((sum, e) => sum + e.amount, 0);
  const totalTaxAmount = periodExpenses.reduce((sum, e) => sum + e.taxAmount, 0);
  const reimbursedAmount = periodExpenses.filter(e => e.status === 'reimbursed').reduce((sum, e) => sum + e.amount, 0);
  const pendingAmount = periodExpenses.filter(e => e.status === 'submitted' || e.status === 'manager_approved').reduce((sum, e) => sum + e.amount, 0);

  // Group by category
  const categoryBreakdown: Record<string, { count: number; total: number }> = {};
  periodExpenses.forEach(exp => {
    if (!categoryBreakdown[exp.category]) {
      categoryBreakdown[exp.category] = { count: 0, total: 0 };
    }
    categoryBreakdown[exp.category].count += 1;
    categoryBreakdown[exp.category].total += exp.amount;
  });

  // Group by department
  const deptBreakdown: Record<string, { count: number; total: number }> = {};
  periodExpenses.forEach(exp => {
    if (!deptBreakdown[exp.department]) {
      deptBreakdown[exp.department] = { count: 0, total: 0 };
    }
    deptBreakdown[exp.department].count += 1;
    deptBreakdown[exp.department].total += exp.amount;
  });

  const handleExportAccountingReportCSV = () => {
    const lines: string[] = [];
    lines.push(`HPC ENTERPRISE - MONTHLY ACCOUNTING & FINANCIAL AUDIT REPORT`);
    lines.push(`Reporting Period: ${selectedMonth} | Generated for Department: ${selectedDept}`);
    lines.push(`Generated by: ${currentUser.name} (${currentUser.designation})`);
    lines.push(`Generated At: ${new Date().toISOString()}`);
    lines.push('');
    lines.push(`Executive Summary:`);
    lines.push(`Total Operating Expenses,${totalExpenseAmount.toFixed(2)} AED`);
    lines.push(`Reimbursed to Date,${reimbursedAmount.toFixed(2)} AED`);
    lines.push(`Pending Approvals,${pendingAmount.toFixed(2)} AED`);
    lines.push(`Input VAT / Recoverable Tax,${totalTaxAmount.toFixed(2)} AED`);
    lines.push('');
    lines.push('Category Breakdown:');
    lines.push('Category,Claim Count,Total Amount (AED),% of Total');
    Object.entries(categoryBreakdown).forEach(([cat, data]) => {
      const pct = totalExpenseAmount > 0 ? ((data.total / totalExpenseAmount) * 100).toFixed(1) : '0';
      lines.push(`"${cat}",${data.count},${data.total.toFixed(2)},${pct}%`);
    });
    lines.push('');
    lines.push('Itemized Claims:');
    lines.push('Claim ID,Date,Employee,Department,Merchant,Category,Amount (AED),VAT (AED),Status,Payment Method');
    periodExpenses.forEach(e => {
      lines.push([
        `"${e.expenseNumber}"`,
        `"${e.date}"`,
        `"${e.employeeName}"`,
        `"${e.department}"`,
        `"${e.merchant}"`,
        `"${e.category}"`,
        e.amount.toFixed(2),
        e.taxAmount.toFixed(2),
        `"${e.status}"`,
        `"${e.reimbursementMethod}"`
      ].join(','));
    });

    downloadCSV(`HPC_Monthly_Financial_Report_${selectedMonth}.csv`, lines.join('\r\n'));
  };

  return (
    <div className="space-y-6">
      
      {/* Top Banner and Controls */}
      <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-xs">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-xl font-bold text-slate-900">
                Administrator Financial Reports &amp; Audit
              </h1>
              <span className="text-[11px] font-semibold text-slate-700 bg-slate-100 px-2 py-0.5 rounded-md border border-slate-200">
                Accounting Portal
              </span>
            </div>
            <p className="text-xs text-slate-500 mt-1">
              Monthly enterprise expense reconciliation, recoverable tax schedule, and board report generation
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2.5">
            {/* Period Selector */}
            <div className="flex items-center gap-1.5 text-xs bg-slate-50 border border-slate-200 px-2.5 py-1.5 rounded-lg">
              <Calendar className="w-3.5 h-3.5 text-slate-500" />
              <select
                value={selectedMonth}
                onChange={(e) => setSelectedMonth(e.target.value)}
                className="bg-transparent font-semibold text-slate-800 focus:outline-hidden"
              >
                <option value="2026-10">October 2026</option>
                <option value="2026-09">September 2026</option>
                <option value="2026-08">August 2026</option>
                <option value="ALL">Full Fiscal Year 2026</option>
              </select>
            </div>

            {/* Department Selector */}
            <div className="flex items-center gap-1.5 text-xs bg-slate-50 border border-slate-200 px-2.5 py-1.5 rounded-lg">
              <Building className="w-3.5 h-3.5 text-slate-500" />
              <select
                value={selectedDept}
                onChange={(e) => setSelectedDept(e.target.value)}
                className="bg-transparent font-semibold text-slate-800 focus:outline-hidden"
              >
                <option value="All">All Departments</option>
                <option value="Client Visa & Global Processing">Client Visa &amp; Processing</option>
                <option value="Operations & Processing">Operations &amp; Processing</option>
                <option value="Corporate Finance & Board">Corporate Finance &amp; Board</option>
              </select>
            </div>

            {/* Actions */}
            <button
              onClick={() => setIsReportModalOpen(true)}
              className="inline-flex items-center gap-1.5 px-3.5 py-2 text-xs font-semibold text-white bg-slate-900 hover:bg-slate-800 rounded-lg transition-colors shadow-xs"
            >
              <FileSpreadsheet className="w-3.5 h-3.5" />
              <span>Generate Monthly Report</span>
            </button>

            <button
              onClick={handleExportAccountingReportCSV}
              className="inline-flex items-center gap-1.5 px-3 py-2 text-xs font-semibold text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors"
            >
              <Download className="w-3.5 h-3.5 text-slate-600" />
              <span>Export Accounting CSV</span>
            </button>
          </div>
        </div>

        {/* 4 Financial KPIs */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-6 pt-5 border-t border-slate-100">
          
          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200">
            <span className="text-[11px] font-semibold text-slate-500 uppercase tracking-wider block">
              Total Period Claims
            </span>
            <div className="text-2xl font-bold font-mono tabular-nums text-slate-900 mt-1">
              {totalExpenseAmount.toLocaleString(undefined, { minimumFractionDigits: 2 })} <span className="text-xs text-slate-500 font-sans font-normal">AED</span>
            </div>
            <span className="text-[11px] text-slate-500 mt-1 block">
              {periodExpenses.length} audited expense receipts
            </span>
          </div>

          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200">
            <span className="text-[11px] font-semibold text-emerald-700 uppercase tracking-wider block">
              Disbursed Reimbursements
            </span>
            <div className="text-2xl font-bold font-mono tabular-nums text-slate-900 mt-1">
              {reimbursedAmount.toLocaleString(undefined, { minimumFractionDigits: 2 })} <span className="text-xs text-slate-500 font-sans font-normal">AED</span>
            </div>
            <span className="text-[11px] text-emerald-700 font-medium mt-1 block">
              {totalExpenseAmount > 0 ? ((reimbursedAmount / totalExpenseAmount) * 100).toFixed(0) : 0}% cleared via corporate account
            </span>
          </div>

          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200">
            <span className="text-[11px] font-semibold text-amber-700 uppercase tracking-wider block">
              In Approval &amp; Processing
            </span>
            <div className="text-2xl font-bold font-mono tabular-nums text-slate-900 mt-1">
              {pendingAmount.toLocaleString(undefined, { minimumFractionDigits: 2 })} <span className="text-xs text-slate-500 font-sans font-normal">AED</span>
            </div>
            <span className="text-[11px] text-amber-700 font-medium mt-1 block">
              Committed liability awaiting clearance
            </span>
          </div>

          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200">
            <span className="text-[11px] font-semibold text-blue-700 uppercase tracking-wider block">
              Input VAT Recoverable
            </span>
            <div className="text-2xl font-bold font-mono tabular-nums text-slate-900 mt-1">
              {totalTaxAmount.toLocaleString(undefined, { minimumFractionDigits: 2 })} <span className="text-xs text-slate-500 font-sans font-normal">AED</span>
            </div>
            <span className="text-[11px] text-blue-700 font-medium mt-1 block">
              Eligible for corporate tax filing credit
            </span>
          </div>

        </div>
      </div>

      {/* Analytics Breakdown Grid: Spending by Category & Spending by Department */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        {/* Category Breakdown */}
        <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs">
          <div className="flex items-center justify-between mb-4 pb-2 border-b border-slate-100">
            <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider">
              Expense Distribution by Category
            </h3>
            <span className="text-[11px] text-slate-400">Total: {totalExpenseAmount.toLocaleString()} AED</span>
          </div>

          <div className="space-y-3">
            {Object.entries(categoryBreakdown).map(([cat, data]) => {
              const percentage = totalExpenseAmount > 0 ? (data.total / totalExpenseAmount) * 100 : 0;
              return (
                <div key={cat} className="space-y-1">
                  <div className="flex items-center justify-between text-xs">
                    <span className="font-semibold text-slate-800">{cat} ({data.count})</span>
                    <span className="font-mono font-bold text-slate-900 tabular-nums">
                      {data.total.toLocaleString(undefined, { minimumFractionDigits: 2 })} AED ({percentage.toFixed(1)}%)
                    </span>
                  </div>
                  <div className="w-full h-2 bg-slate-100 rounded-full overflow-hidden">
                    <div 
                      className="h-full bg-slate-900 rounded-full transition-all duration-300"
                      style={{ width: `${Math.max(4, percentage)}%` }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Department Breakdown */}
        <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs">
          <div className="flex items-center justify-between mb-4 pb-2 border-b border-slate-100">
            <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider">
              Expense Distribution by Department
            </h3>
            <span className="text-[11px] text-slate-400">Audit Allocation</span>
          </div>

          <div className="space-y-3">
            {Object.entries(deptBreakdown).map(([dept, data]) => {
              const percentage = totalExpenseAmount > 0 ? (data.total / totalExpenseAmount) * 100 : 0;
              return (
                <div key={dept} className="space-y-1">
                  <div className="flex items-center justify-between text-xs">
                    <span className="font-semibold text-slate-800">{dept}</span>
                    <span className="font-mono font-bold text-slate-900 tabular-nums">
                      {data.total.toLocaleString(undefined, { minimumFractionDigits: 2 })} AED ({percentage.toFixed(1)}%)
                    </span>
                  </div>
                  <div className="w-full h-2 bg-slate-100 rounded-full overflow-hidden">
                    <div 
                      className="h-full bg-emerald-700 rounded-full transition-all duration-300"
                      style={{ width: `${Math.max(4, percentage)}%` }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </div>

      </div>

      {/* Monthly Report Full Preview & Print / PDF Modal */}
      {isReportModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/60 backdrop-blur-xs overflow-y-auto">
          <div className="bg-white rounded-2xl shadow-2xl max-w-4xl w-full p-8 border border-slate-200 my-8 print-break-inside-avoid">
            
            {/* Report Header */}
            <div className="flex items-start justify-between border-b-2 border-slate-900 pb-5">
              <div>
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-lg bg-slate-900 text-white flex items-center justify-center font-bold text-xs">
                    HPC
                  </div>
                  <span className="text-lg font-black tracking-tight text-slate-900">
                    HPC OFFICE &amp; VISA SERVICES LLC
                  </span>
                </div>
                <h2 className="text-xl font-bold text-slate-900 mt-2">
                  Executive Monthly Financial &amp; Expense Audit Report
                </h2>
                <p className="text-xs text-slate-500">
                  Fiscal Period: <strong className="text-slate-800">{selectedMonth}</strong> · Department Scope: <strong className="text-slate-800">{selectedDept}</strong>
                </p>
              </div>

              <div className="text-right">
                <span className="font-mono text-xs text-slate-400 block">DOCUMENT: HPC-FIN-2026-M10</span>
                <span className="font-mono text-xs text-emerald-700 font-bold block mt-0.5">STATUS: AUDITED &amp; VERIFIED</span>
                <div className="flex items-center justify-end gap-2 mt-3 no-print">
                  <button
                    onClick={() => window.print()}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-white bg-slate-900 hover:bg-slate-800 rounded-lg shadow-xs"
                  >
                    <Printer className="w-3.5 h-3.5" />
                    <span>Print / Save PDF</span>
                  </button>
                  <button
                    onClick={handleExportAccountingReportCSV}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>CSV</span>
                  </button>
                  <button
                    onClick={() => setIsReportModalOpen(false)}
                    className="px-3 py-1.5 text-xs font-semibold text-slate-600 hover:bg-slate-100 rounded-lg"
                  >
                    Close
                  </button>
                </div>
              </div>
            </div>

            {/* Financial Summary Table */}
            <div className="mt-6 space-y-4">
              <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wider">
                1. Executive Financial Summary
              </h4>
              <div className="grid grid-cols-4 gap-4 p-4 bg-slate-50 rounded-xl border border-slate-200 text-xs">
                <div>
                  <span className="text-slate-500 block text-[11px]">Total Gross Claims</span>
                  <span className="font-mono font-bold text-base text-slate-900">{totalExpenseAmount.toLocaleString()} AED</span>
                </div>
                <div>
                  <span className="text-slate-500 block text-[11px]">Reimbursed from Bank</span>
                  <span className="font-mono font-bold text-base text-emerald-800">{reimbursedAmount.toLocaleString()} AED</span>
                </div>
                <div>
                  <span className="text-slate-500 block text-[11px]">Input Tax / VAT Credit</span>
                  <span className="font-mono font-bold text-base text-blue-800">{totalTaxAmount.toLocaleString()} AED</span>
                </div>
                <div>
                  <span className="text-slate-500 block text-[11px]">Daily Petty Cash Balance</span>
                  <span className="font-mono font-bold text-base text-slate-900">{reconciliation.cashInHand.toLocaleString()} AED</span>
                </div>
              </div>
            </div>

            {/* Itemized Audit Ledger */}
            <div className="mt-6 space-y-3">
              <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wider">
                2. Itemized Claims Audit Ledger ({periodExpenses.length} Records)
              </h4>
              <table className="w-full text-left text-xs border border-slate-200">
                <thead>
                  <tr className="bg-slate-100 border-b border-slate-200 font-bold text-slate-700">
                    <th className="py-2 px-3">Claim ID</th>
                    <th className="py-2 px-3">Date</th>
                    <th className="py-2 px-3">Claimant</th>
                    <th className="py-2 px-3">Merchant / Purpose</th>
                    <th className="py-2 px-3">Category</th>
                    <th className="py-2 px-3 text-right">Amount (AED)</th>
                    <th className="py-2 px-3 text-right">VAT</th>
                    <th className="py-2 px-3">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {periodExpenses.map(e => (
                    <tr key={e.id}>
                      <td className="py-2 px-3 font-mono font-semibold">{e.expenseNumber}</td>
                      <td className="py-2 px-3 font-mono">{e.date}</td>
                      <td className="py-2 px-3">{e.employeeName}</td>
                      <td className="py-2 px-3">{e.merchant}</td>
                      <td className="py-2 px-3">{e.category}</td>
                      <td className="py-2 px-3 text-right font-mono tabular-nums font-semibold">{e.amount.toFixed(2)}</td>
                      <td className="py-2 px-3 text-right font-mono tabular-nums">{e.taxAmount.toFixed(2)}</td>
                      <td className="py-2 px-3 uppercase text-[10px] font-bold">{e.status}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Corporate Sign-off Block */}
            <div className="mt-8 pt-6 border-t border-slate-200 grid grid-cols-3 gap-6 text-xs">
              <div>
                <span className="text-slate-400 block text-[11px]">Prepared by:</span>
                <p className="font-semibold text-slate-900 mt-1">{currentUser.name}</p>
                <p className="text-[11px] text-slate-500">{currentUser.designation}</p>
                <div className="w-40 border-b border-slate-300 mt-6"></div>
                <span className="text-[10px] text-slate-400">Signature &amp; Date</span>
              </div>

              <div>
                <span className="text-slate-400 block text-[11px]">Department Manager Verification:</span>
                <p className="font-semibold text-slate-900 mt-1">Sarah Chen</p>
                <p className="text-[11px] text-slate-500">Department Operations Manager</p>
                <div className="w-40 border-b border-slate-300 mt-6"></div>
                <span className="text-[10px] text-slate-400">Signature &amp; Date</span>
              </div>

              <div>
                <span className="text-slate-400 block text-[11px]">Board &amp; CFO Clearance:</span>
                <p className="font-semibold text-slate-900 mt-1">Dilip Sharma</p>
                <p className="text-[11px] text-slate-500">Chief Financial Officer</p>
                <div className="w-40 border-b border-slate-300 mt-6"></div>
                <span className="text-[10px] text-slate-400">Corporate Seal &amp; Authorization</span>
              </div>
            </div>

          </div>
        </div>
      )}

    </div>
  );
};
